name: weather_summary
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  dart_openai: ^3.0.0
  geolocator: ^9.0.2
  intl: ^0.18.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  flutter_riverpod: ^2.3.6
  sliding_up_panel: ^2.0.0+1
  chat_gpt_sdk: ^2.2.3
  speech_to_text: ^6.3.0
  translator: ^0.1.7
  flutter_tts: ^3.7.0
  perfect_volume_control: ^1.0.5
  geocoding: ^2.1.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.7.0
  flutter_local_notifications: ^15.0.1
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/.
    - assets/icon/.
    - assets/items/.
    - assets/weather_mini/.
    - assets/home/.
    - assets/weather/.
    - assets/lottie/97952-loading-animation-blue.json
    - assets/toggle/toggle_down.png
    - assets/toggle/toggle_up.png
    - assets/toggle/Button_briefing.png
    - assets/icon/setting.png
    - assets/icon/icon_drop.png
    - assets/toggle/Button_chatbot.png
    - assets/icon/plus.png

  fonts:
    - family: "NanumGothic-Light"
      fonts:
        - asset: assets/fonts/NanumGothic-Light.ttf
    - family: "NanumGothic-Regular"
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
    - family: "NanumGothic-Bold"
      fonts:
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700
    - family: "NanumGothic-ExtraBold"
      fonts:
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 900
    - family: "paybooc Bold"
      fonts:
        - asset: "assets/fonts/paybooc Bold.ttf"
    - family: "paybooc ExtraBold"
      fonts:
        - asset: "assets/fonts/paybooc ExtraBold.ttf"
    - family: "paybooc Light"
      fonts:
        - asset: "assets/fonts/paybooc Light.ttf"
    - family: "paybooc Medium"
      fonts:
        - asset: "assets/fonts/paybooc Medium.ttf"
          weight: 500